# Generated by Django 5.0.6 on 2024-05-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lunch_category', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=100)),
                ('dinner_category', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=100)),
                ('plan_days', models.IntegerField(choices=[(3, '3 Days'), (7, '7 Days'), (15, '15 Days'), (30, '30 Days')])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meals_consumed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MealPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_lunch_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium_lunch_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_dinner_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('premium_dinner_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch_off', models.BooleanField(default=False)),
                ('dinner_off', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customer')),
            ],
        ),
    ]
